### ISSUE TITLE
Lockup on europa v1.0 (RC2) - CI Compact (VMWare)

### ISSUE THREAD

**Issue by mike-williams** [gatblau/neus#9]
Hi, I am having issues with trying to generate the docker CI image from within the europa vm. The dependencies all fully download into the cache folder but after that nothing happens. 

It seems that the script moves onto running packer: 
packer build ci-compact-vmware.json

At this point the command doesnt return. When running packer on commandline (packer --version) it doesnt return either. I have downloaded a seperate packer executable and that responds to packer --version.

**Comment by gatblau** [comment]
Hi Mike, I have changed the structure of the project. The docker CI image will not be available going forward.Rather, the approach will be to have 4 blueprints for VMs (Bronze to Platinum) and 1 for container orchestration engines (Silicon). The silicon blueprint will have 1 image per service, whereas the VM blueprints will be tested in privileged containers within Europa. 
This is being worked on at this minute.
